    public enum TokenType{
    //SINGLE CHARACTERS
    TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN,
    TOKEN_LEFT_BRACE, TOKEN_RIGH_BRACE,
    TOKEN_COMMA, TOKEN_DOT, TOKEN_MINUS, TOKEN_PLUS,
    TOKEN_SEMICOLON, TOKEN_SLASH, TOKEN_STAR,

    //More than one characters
    TOKEN_BANG, TOKEN_BANG_EQUAL, //BANG -> !
    TOKEN_EQUAL, TOKEN_EQUAL_EQUAL,
    TOKEN_GREATER_EQUAL, TOKEN_GREATER, 
    TOKEN_LESS, TOKEN_LESS_EQUAL,

    //literals -> identifiers, numbers , strings
    TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_NUMBER,

    //keywords
    TOKEN_AND, TOKEN_CLASS, TOKEN_ELSE, TOKEN_FALSE,
    TOKEN_FOR, TOKEN_FUN, TOKEN_IF,  TOKEN_NIL,
    TOKEN_OR, TOKEN_PRINT, TOKEN_RETURN, TOKEN_SUPER,
    TOKEN_THIS, TOKEN_TRUE, TOKEN_VAR, TOKEN_WHILE,

    TOKEN_ERROR, TOKEN_EOF
}